Pin Arch package to build-time Qt ABI

diff --git a/arch/PKGBUILD b/arch/PKGBUILD
--- a/arch/PKGBUILD
+++ b/arch/PKGBUILD
@@ -3,7 +3,7 @@
 
 pkgname=powerdevil
 pkgver=6.6.4
-pkgrel=13
+pkgrel=14
 pkgdesc='Manages the power consumption settings of a Plasma Shell (DDC brightness range guard)'
 arch=(x86_64)
 url='https://github.com/JSJ-Experiments/powerdevil-ddc-brightness-fix'
@@ -30,5 +30,19 @@ build() {
 }
 
 package() {
+  # QML plugins use Qt's private C++ ABI. A package built on a newer Arch
+  # image can fail to load on a host with an older Qt, even at the same Plasma
+  # version. Require the exact Qt builds used for this package.
+  local qt_base_version qt_declarative_version
+  qt_base_version=$(pacman -Q qt6-base | awk '{print $2}') || return
+  qt_declarative_version=$(pacman -Q qt6-declarative | awk '{print $2}') || return
+  [[ -n $qt_base_version && -n $qt_declarative_version ]] || return 1
+  local i
+  for i in "${!depends[@]}"; do
+    case ${depends[i]} in
+      qt6-base) depends[i]="qt6-base=$qt_base_version" ;;
+      qt6-declarative) depends[i]="qt6-declarative=$qt_declarative_version" ;;
+    esac
+  done
   DESTDIR="$pkgdir" cmake --install build
 }
